# flake.module.nix — project-specific flake-parts customizations for keiki.
#
# seihou does NOT manage this file: it is never regenerated or overwritten by
# `seihou run` or by nix-haskell-flake migrations, so it is the conflict-free
# home for every customization that must survive template upgrades. See
# flake.module.nix.example (generated by the module) for the full option list.
#
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ REQUIRED: this file MUST be git-tracked (`git add flake.module.nix`).     │
# │ Nix flakes evaluate only files tracked by git, so flake.nix's             │
# │ `builtins.pathExists ./flake.module.nix` import guard sees an untracked   │
# │ file as ABSENT and silently ignores everything below — no error, the      │
# │ customization just vanishes from the dev shell. After `git add`, prove it │
# │ took effect with `nix print-dev-env | grep <tool>`.                       │
# └──────────────────────────────────────────────────────────────────────────┘
{ inputs, ... }:
{
  perSystem = { system, pkgs, config, ... }:
    let
      hsdev = inputs.haskell-nix-dev.lib.${system};
    in
    {
      # Project-specific dev-shell tools, layered onto the managed baseDevPackages
      # in ./nix/haskell.nix (which reads config.haskellProject.extraDevPackages).
      #
      #   nodejs_22 + pnpm: the docs/site build (see justfile: `pnpm run build`,
      #                     `node site/check-links.mjs`).
      #   z3:               the SMT solver keiki's specs are written against; the
      #                     dev shell pins it so it stays identical across machines.
      haskellProject.extraDevPackages = [
        pkgs.nodejs_22
        pkgs.pnpm
        pkgs.z3
      ];

      # CI dev shell, consumed by .github/workflows/ci.yml (`nix develop .#ci`).
      # It carries the SAME toolchain and the SAME extra tool list as the default
      # shell — that parity is the point; it is what keeps CI's z3 identical to
      # the one specs are written against — but drops two things a batch job does
      # not want: HLS (a large closure no CI job invokes) and the pre-commit hook
      # install (it writes into .git/hooks and only makes sense for a working
      # tree, so the shellHook is omitted here).
      devShells.ci = hsdev.mkDevShell {
        ghc = "ghc9124";
        withHls = false;
        extraNativeBuildInputs =
          [
            pkgs.zlib
            pkgs.just
            pkgs.pkg-config
          ]
          ++ config.haskellProject.extraDevPackages;
      };

      # Pin fourmolu to the ghc9124 package set so `nix fmt` / the treefmt check
      # / the pre-commit treefmt hook all use the same fourmolu the project is
      # formatted against, instead of treefmt-nix's default (which tracks the
      # default GHC's fourmolu and can drift the style). flake-parts merges
      # treefmt.* options across modules, so this overrides only the package
      # without touching the managed ./nix/treefmt.nix.
      treefmt.programs.fourmolu.package = pkgs.haskell.packages.ghc9124.fourmolu;
    };
}
