stateDiagram-v2
    [*] --> SpecialStart
    SpecialStart --> SpecialDone : Command &quot;quote&quot; &apos;apostrophe&apos; ＜br＞ ＜br/＞ ＜br /＞ &amp;lt;br&amp;gt; &#124; &#123;value&#125;␍␊＼n / Event<br/>u: (keep)<br/>g: Command &quot;quote&quot; &apos;apostrophe&apos; ＜br＞ ＜br/＞ ＜br /＞ &amp;lt;br&amp;gt; &#124; &#123;value&#125;␍␊＼n
    SpecialDone --> [*]
