{-# LANGUAGE GADTs #-}
{-# LANGUAGE PolyKinds #-}

-- | The User Registration aggregate from synthesis §4, transcribed in
-- the v1 'Keiki.Core' DSL. This module is the smoke test for the
-- master plan's "the synthesis holds" gate.
--
-- See:
--
--   * @docs/research/synthesis-c-foundation-b-presentation-with-worked-examples.md@
--     §4 — the original walkthrough.
--   * @docs/research/dsl-shape-for-symbolic-register.md@ — the DSL note's
--     "Worked example" section, which this module reproduces.
--
-- v1 deviations from synthesis §4:
--
--   * 'AccountConfirmedData' carries the @confirmCode@ field (synthesis
--     §4 fix-1). This is the "fixed" schema. The "unfixed" schema —
--     'Keiki.Examples.UserRegistrationV0' — is a separate module that
--     drops the field for the M7 hidden-input demonstration.
--   * 'ResendConfirmationData' carries a @code@ field (the new
--     confirmation code). Per the EP-3 effects-boundary note, fresh
--     codes are generated by the runtime adapter, not pulled from
--     'IO' inside the transducer.
--   * Each output is built with 'OPack' plus a v1 hand-written
--     inverse. The DSL note's 'OPack' was extended in M4 to carry that
--     inverse; see EP-4's Decision Log.
module Keiki.Examples.UserRegistration
  ( -- * Domain types
    Email
  , ConfirmationCode
    -- * Command payloads
  , StartRegistrationData (..)
  , ConfirmAccountData (..)
  , ResendConfirmationData (..)
  , FulfillGDPRRequestData (..)
  , UserCmd (..)
    -- * Event payloads
  , RegistrationStartedData (..)
  , ConfirmationEmailSentData (..)
  , AccountConfirmedData (..)
  , ConfirmationResentData (..)
  , AccountDeletedData (..)
  , UserEvent (..)
    -- * Register file and control vertices
  , UserRegRegs
  , Vertex (..)
    -- * The transducer
  , userReg
  , emptyRegs
    -- * Wire constructors (exported for testing)
  , wireRegistrationStarted
  , wireConfirmationEmailSent
  , wireAccountConfirmed
  , wireConfirmationResent
  , wireAccountDeleted
    -- * Input constructors (exported for testing and reuse)
  , inCtorStart
  , inCtorConfirm
  , inCtorResend
  , inCtorGdpr
  , inCtorContinue
  , inpStart
  , inpConfirm
  , inpResend
  , inpGdpr
  ) where

import Data.Proxy (Proxy (..))
import Data.Text (Text)
import Data.Time (UTCTime)
import Keiki.Core


-- * Domain types ------------------------------------------------------------

type Email            = Text
type ConfirmationCode = Text


-- * Command payloads --------------------------------------------------------

data StartRegistrationData = StartRegistrationData
  { email       :: Email
  , confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show)

data ConfirmAccountData = ConfirmAccountData
  { confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show)

-- | Per the effects-boundary note: fresh confirmation codes are
-- generated by the runtime adapter and arrive in the command. The
-- pure layer never pulls randomness.
data ResendConfirmationData = ResendConfirmationData
  { code :: ConfirmationCode
  , at   :: UTCTime
  } deriving (Eq, Show)

newtype FulfillGDPRRequestData = FulfillGDPRRequestData { at :: UTCTime }
  deriving (Eq, Show)

data UserCmd
  = StartRegistration  StartRegistrationData
  | ConfirmAccount     ConfirmAccountData
  | ResendConfirmation ResendConfirmationData
  | FulfillGDPRRequest FulfillGDPRRequestData
  | Continue
  deriving (Eq, Show)


-- * Event payloads ----------------------------------------------------------

data RegistrationStartedData = RegistrationStartedData
  { email       :: Email
  , confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show)

newtype ConfirmationEmailSentData = ConfirmationEmailSentData { email :: Email }
  deriving (Eq, Show)

-- | Synthesis §4 fix-1 schema: includes the @confirmCode@ field.
data AccountConfirmedData = AccountConfirmedData
  { email       :: Email
  , confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show)

data ConfirmationResentData = ConfirmationResentData
  { email       :: Email
  , confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show)

data AccountDeletedData = AccountDeletedData
  { email :: Email
  , at    :: UTCTime
  } deriving (Eq, Show)

data UserEvent
  = RegistrationStarted   RegistrationStartedData
  | ConfirmationEmailSent ConfirmationEmailSentData
  | AccountConfirmed      AccountConfirmedData
  | ConfirmationResent    ConfirmationResentData
  | AccountDeleted        AccountDeletedData
  deriving (Eq, Show)


-- * Register file and control vertices -------------------------------------

type UserRegRegs =
  '[ '("email",        Email)
   , '("confirmCode",  ConfirmationCode)
   , '("registeredAt", UTCTime)
   , '("confirmedAt",  UTCTime)
   , '("deletedAt",    UTCTime)
   ]


data Vertex
  = PotentialCustomer
  | Registering
  | RequiresConfirmation
  | Confirmed
  | Deleted
  deriving (Eq, Show, Enum, Bounded)


-- | Initial register file. Slots are pre-bound to deferred errors so
-- that the type checks; reads of an uninitialized slot crash with a
-- targeted message rather than silently returning bottom.
emptyRegs :: RegFile UserRegRegs
emptyRegs =
  RCons (Proxy @"email")        (error "uninit: email")
  $ RCons (Proxy @"confirmCode")  (error "uninit: confirmCode")
  $ RCons (Proxy @"registeredAt") (error "uninit: registeredAt")
  $ RCons (Proxy @"confirmedAt")  (error "uninit: confirmedAt")
  $ RCons (Proxy @"deletedAt")    (error "uninit: deletedAt")
  $ RNil


-- * Per-constructor input projections (v2 structural surface) -------------
--
-- One 'InCtor' value per command constructor describes how to match
-- and re-build the constructor's payload as a typed 'RegFile'. The
-- per-constructor 'inpFoo' helpers turn an 'Index' (typically written
-- via 'OverloadedLabels' as @inpStart #email@) into a 'Term' that
-- structurally projects the named field of the named command
-- constructor. 'solveOutput' walks the 'OutFields' bound by an edge's
-- @output@ and reconstructs the input @ci@ mechanically; no per-edge
-- inverse function is needed.

type StartFields   =
  '[ '("email", Email)
   , '("confirmCode", ConfirmationCode)
   , '("at", UTCTime)
   ]

type ConfirmFields =
  '[ '("confirmCode", ConfirmationCode)
   , '("at", UTCTime)
   ]

type ResendFields  =
  '[ '("code", ConfirmationCode)
   , '("at", UTCTime)
   ]

type GdprFields    =
  '[ '("at", UTCTime) ]


inCtorStart :: InCtor UserCmd StartFields
inCtorStart = InCtor
  { icName  = "StartRegistration"
  , icMatch = \case
      StartRegistration d ->
        Just (RCons (Proxy @"email")       d.email
            $ RCons (Proxy @"confirmCode") d.confirmCode
            $ RCons (Proxy @"at")          d.at
            $ RNil)
      _ -> Nothing
  , icBuild = \(RCons _ e (RCons _ cc (RCons _ a RNil))) ->
                StartRegistration (StartRegistrationData e cc a)
  }


inCtorConfirm :: InCtor UserCmd ConfirmFields
inCtorConfirm = InCtor
  { icName  = "ConfirmAccount"
  , icMatch = \case
      ConfirmAccount d ->
        Just (RCons (Proxy @"confirmCode") d.confirmCode
            $ RCons (Proxy @"at")          d.at
            $ RNil)
      _ -> Nothing
  , icBuild = \(RCons _ cc (RCons _ a RNil)) ->
                ConfirmAccount (ConfirmAccountData cc a)
  }


inCtorResend :: InCtor UserCmd ResendFields
inCtorResend = InCtor
  { icName  = "ResendConfirmation"
  , icMatch = \case
      ResendConfirmation d ->
        Just (RCons (Proxy @"code") d.code
            $ RCons (Proxy @"at")   d.at
            $ RNil)
      _ -> Nothing
  , icBuild = \(RCons _ c (RCons _ a RNil)) ->
                ResendConfirmation (ResendConfirmationData c a)
  }


inCtorGdpr :: InCtor UserCmd GdprFields
inCtorGdpr = InCtor
  { icName  = "FulfillGDPRRequest"
  , icMatch = \case
      FulfillGDPRRequest d ->
        Just (RCons (Proxy @"at") d.at $ RNil)
      _ -> Nothing
  , icBuild = \(RCons _ a RNil) ->
                FulfillGDPRRequest (FulfillGDPRRequestData a)
  }


-- | The 'Continue' command has no payload, so its 'InCtor' has the
-- empty slot list. The structural inverse recovers @Continue@ from
-- @icBuild inCtorContinue RNil@.
inCtorContinue :: InCtor UserCmd '[]
inCtorContinue = InCtor
  { icName  = "Continue"
  , icMatch = \case
      Continue -> Just RNil
      _        -> Nothing
  , icBuild = \RNil -> Continue
  }


inpStart   :: Index StartFields   r -> Term UserRegRegs UserCmd r
inpStart    = TInpCtorField inCtorStart

inpConfirm :: Index ConfirmFields r -> Term UserRegRegs UserCmd r
inpConfirm  = TInpCtorField inCtorConfirm

inpResend  :: Index ResendFields  r -> Term UserRegRegs UserCmd r
inpResend   = TInpCtorField inCtorResend

inpGdpr    :: Index GdprFields    r -> Term UserRegRegs UserCmd r
inpGdpr     = TInpCtorField inCtorGdpr


-- * Per-constructor guards -------------------------------------------------

isStart, isConfirm, isResend, isGdpr, isContinue
  :: HsPred UserRegRegs UserCmd
isStart    = matchCmd $ \case StartRegistration{}  -> True; _ -> False
isConfirm  = matchCmd $ \case ConfirmAccount{}     -> True; _ -> False
isResend   = matchCmd $ \case ResendConfirmation{} -> True; _ -> False
isGdpr     = matchCmd $ \case FulfillGDPRRequest{} -> True; _ -> False
isContinue = matchCmd $ \case Continue             -> True; _ -> False


-- * Wire constructors for events -------------------------------------------

wireRegistrationStarted
  :: WireCtor UserEvent (Email, (ConfirmationCode, (UTCTime, ())))
wireRegistrationStarted = WireCtor
  { wcName  = "RegistrationStarted"
  , wcMatch = \case
      RegistrationStarted d ->
        Just (d.email, (d.confirmCode, (d.at, ())))
      _ -> Nothing
  , wcBuild = \(e, (cc, (a, ()))) ->
      RegistrationStarted (RegistrationStartedData e cc a)
  }


wireConfirmationEmailSent
  :: WireCtor UserEvent (Email, ())
wireConfirmationEmailSent = WireCtor
  { wcName  = "ConfirmationEmailSent"
  , wcMatch = \case
      ConfirmationEmailSent d -> Just (d.email, ())
      _ -> Nothing
  , wcBuild = \(e, ()) ->
      ConfirmationEmailSent (ConfirmationEmailSentData e)
  }


wireAccountConfirmed
  :: WireCtor UserEvent (Email, (ConfirmationCode, (UTCTime, ())))
wireAccountConfirmed = WireCtor
  { wcName  = "AccountConfirmed"
  , wcMatch = \case
      AccountConfirmed d ->
        Just (d.email, (d.confirmCode, (d.at, ())))
      _ -> Nothing
  , wcBuild = \(e, (cc, (a, ()))) ->
      AccountConfirmed (AccountConfirmedData e cc a)
  }


wireConfirmationResent
  :: WireCtor UserEvent (Email, (ConfirmationCode, (UTCTime, ())))
wireConfirmationResent = WireCtor
  { wcName  = "ConfirmationResent"
  , wcMatch = \case
      ConfirmationResent d ->
        Just (d.email, (d.confirmCode, (d.at, ())))
      _ -> Nothing
  , wcBuild = \(e, (cc, (a, ()))) ->
      ConfirmationResent (ConfirmationResentData e cc a)
  }


wireAccountDeleted
  :: WireCtor UserEvent (Email, (UTCTime, ()))
wireAccountDeleted = WireCtor
  { wcName  = "AccountDeleted"
  , wcMatch = \case
      AccountDeleted d -> Just (d.email, (d.at, ()))
      _ -> Nothing
  , wcBuild = \(e, (a, ())) ->
      AccountDeleted (AccountDeletedData e a)
  }


-- * The transducer ---------------------------------------------------------

userReg :: SymTransducer (HsPred UserRegRegs UserCmd)
                         UserRegRegs
                         Vertex
                         UserCmd
                         UserEvent
userReg = SymTransducer
  { edgesOut = userRegEdges
  , initial     = PotentialCustomer
  , initialRegs = emptyRegs
  , isFinal     = \case Deleted -> True; _ -> False
  }


userRegEdges
  :: Vertex
  -> [Edge (HsPred UserRegRegs UserCmd) UserRegRegs UserCmd UserEvent Vertex]
userRegEdges = \case

  PotentialCustomer ->
    [ Edge
        { guard  = isStart
        , update =
            USet (#email :: Index UserRegRegs Email) (inpStart #email)
              `unsafeCombine`
            USet (#confirmCode :: Index UserRegRegs ConfirmationCode)
                 (inpStart #confirmCode)
              `unsafeCombine`
            USet (#registeredAt :: Index UserRegRegs UTCTime)
                 (inpStart #at)
        , output = Just $ pack
            inCtorStart
            wireRegistrationStarted
            (OFCons (inpStart #email)
              (OFCons (inpStart #confirmCode)
                (OFCons (inpStart #at) OFNil)))
        , target = Registering
        }
    ]

  -- Internal Continue command emits ConfirmationEmailSent.
  Registering ->
    [ Edge
        { guard  = isContinue
        , update = UKeep
        , output = Just $ pack
            inCtorContinue
            wireConfirmationEmailSent
            (OFCons (proj (#email :: Index UserRegRegs Email)) OFNil)
        , target = RequiresConfirmation
        }
    ]

  RequiresConfirmation ->
    [ -- Right code: confirm. The 'isConfirm' conjunct short-circuits the
      -- inpConfirm read for non-ConfirmAccount inputs.
      Edge
        { guard  = PAnd isConfirm
            (inpConfirm #confirmCode
              .== proj (#confirmCode :: Index UserRegRegs ConfirmationCode))
        , update = USet (#confirmedAt :: Index UserRegRegs UTCTime)
                        (inpConfirm #at)
        , output = Just $ pack
            inCtorConfirm
            wireAccountConfirmed
            (OFCons (proj (#email :: Index UserRegRegs Email))
              (OFCons (inpConfirm #confirmCode)
                (OFCons (inpConfirm #at) OFNil)))
        , target = Confirmed
        }
      -- Resend: rotate the code (code arrives in the command).
    , Edge
        { guard  = isResend
        , update =
            USet (#confirmCode :: Index UserRegRegs ConfirmationCode)
                 (inpResend #code)
              `unsafeCombine`
            USet (#registeredAt :: Index UserRegRegs UTCTime)
                 (inpResend #at)
        , output = Just $ pack
            inCtorResend
            wireConfirmationResent
            (OFCons (proj (#email :: Index UserRegRegs Email))
              (OFCons (inpResend #code)
                (OFCons (inpResend #at) OFNil)))
        , target = RequiresConfirmation
        }
      -- GDPR before confirmation: silent ε-edge (no event).
    , Edge
        { guard  = isGdpr
        , update = USet (#deletedAt :: Index UserRegRegs UTCTime)
                        (inpGdpr #at)
        , output = Nothing
        , target = Deleted
        }
    ]

  Confirmed ->
    [ Edge
        { guard  = isGdpr
        , update = USet (#deletedAt :: Index UserRegRegs UTCTime)
                        (inpGdpr #at)
        , output = Just $ pack
            inCtorGdpr
            wireAccountDeleted
            (OFCons (proj (#email :: Index UserRegRegs Email))
              (OFCons (inpGdpr #at) OFNil))
        , target = Deleted
        }
    ]

  Deleted -> []
