{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE PolyKinds #-}

-- | The User Registration aggregate from synthesis §4, transcribed in
-- the v1 'Keiki.Core' DSL. This module is the smoke test for the
-- master plan's "the synthesis holds" gate.
--
-- See:
--
--   * @docs/research/synthesis-c-foundation-b-presentation-with-worked-examples.md@
--     §4 — the original walkthrough.
--   * @docs/research/dsl-shape-for-symbolic-register.md@ — the DSL note's
--     "Worked example" section, which this module reproduces.
--
-- v1 deviations from synthesis §4:
--
--   * 'AccountConfirmedData' carries the @confirmCode@ field (synthesis
--     §4 fix-1). This is the "fixed" schema. The "unfixed" schema —
--     'Keiki.Examples.UserRegistrationV0' — is a separate module that
--     drops the field for the M7 hidden-input demonstration.
--   * 'ResendConfirmationData' carries a @code@ field (the new
--     confirmation code). Per the EP-3 effects-boundary note, fresh
--     codes are generated by the runtime adapter, not pulled from
--     'IO' inside the transducer.
--   * Each output is built with 'OPack' plus a v1 hand-written
--     inverse. The DSL note's 'OPack' was extended in M4 to carry that
--     inverse; see EP-4's Decision Log.
module Keiki.Examples.UserRegistration
  ( -- * Domain types
    Email
  , ConfirmationCode
    -- * Command payloads
  , StartRegistrationData (..)
  , ConfirmAccountData (..)
  , ResendConfirmationData (..)
  , FulfillGDPRRequestData (..)
  , UserCmd (..)
    -- * Event payloads
  , RegistrationStartedData (..)
  , ConfirmationEmailSentData (..)
  , AccountConfirmedData (..)
  , ConfirmationResentData (..)
  , AccountDeletedData (..)
  , UserEvent (..)
    -- * Register file and control vertices
  , UserRegRegs
  , Vertex (..)
    -- * The transducer
  , userReg
  , emptyRegs
    -- * Wire constructors (exported for testing)
  , wireRegistrationStarted
  , wireConfirmationEmailSent
  , wireAccountConfirmed
  , wireConfirmationResent
  , wireAccountDeleted
    -- * Input constructors (exported for testing and reuse)
  , inCtorStart
  , inCtorConfirm
  , inCtorResend
  , inCtorGdpr
  , inCtorContinue
  , inpStart
  , inpConfirm
  , inpResend
  , inpGdpr
  ) where

import Data.Text (Text)
import Data.Time (UTCTime)
import GHC.Generics (Generic)
import Keiki.Core
import Keiki.Generics (FieldsOf, emptyRegFile, mkInCtor0, mkInCtorVia, mkWireCtorVia)


-- * Domain types ------------------------------------------------------------

type Email            = Text
type ConfirmationCode = Text


-- * Command payloads --------------------------------------------------------

data StartRegistrationData = StartRegistrationData
  { email       :: Email
  , confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show, Generic)

data ConfirmAccountData = ConfirmAccountData
  { confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show, Generic)

-- | Per the effects-boundary note: fresh confirmation codes are
-- generated by the runtime adapter and arrive in the command. The
-- pure layer never pulls randomness.
data ResendConfirmationData = ResendConfirmationData
  { code :: ConfirmationCode
  , at   :: UTCTime
  } deriving (Eq, Show, Generic)

newtype FulfillGDPRRequestData = FulfillGDPRRequestData { at :: UTCTime }
  deriving (Eq, Show, Generic)

data UserCmd
  = StartRegistration  StartRegistrationData
  | ConfirmAccount     ConfirmAccountData
  | ResendConfirmation ResendConfirmationData
  | FulfillGDPRRequest FulfillGDPRRequestData
  | Continue
  deriving (Eq, Show, Generic)


-- * Event payloads ----------------------------------------------------------

data RegistrationStartedData = RegistrationStartedData
  { email       :: Email
  , confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show, Generic)

newtype ConfirmationEmailSentData = ConfirmationEmailSentData { email :: Email }
  deriving (Eq, Show, Generic)

-- | Synthesis §4 fix-1 schema: includes the @confirmCode@ field.
data AccountConfirmedData = AccountConfirmedData
  { email       :: Email
  , confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show, Generic)

data ConfirmationResentData = ConfirmationResentData
  { email       :: Email
  , confirmCode :: ConfirmationCode
  , at          :: UTCTime
  } deriving (Eq, Show, Generic)

data AccountDeletedData = AccountDeletedData
  { email :: Email
  , at    :: UTCTime
  } deriving (Eq, Show, Generic)

data UserEvent
  = RegistrationStarted   RegistrationStartedData
  | ConfirmationEmailSent ConfirmationEmailSentData
  | AccountConfirmed      AccountConfirmedData
  | ConfirmationResent    ConfirmationResentData
  | AccountDeleted        AccountDeletedData
  deriving (Eq, Show, Generic)


-- * Register file and control vertices -------------------------------------

type UserRegRegs =
  '[ '("email",        Email)
   , '("confirmCode",  ConfirmationCode)
   , '("registeredAt", UTCTime)
   , '("confirmedAt",  UTCTime)
   , '("deletedAt",    UTCTime)
   ]


data Vertex
  = PotentialCustomer
  | Registering
  | RequiresConfirmation
  | Confirmed
  | Deleted
  deriving (Eq, Show, Enum, Bounded)


-- | Initial register file. Each slot is pre-bound to a deferred
-- @"uninit: <slot>"@ error by 'Keiki.Generics.emptyRegFile' so reads
-- of an uninitialized slot crash with a targeted message instead of
-- a silent bottom.
emptyRegs :: RegFile UserRegRegs
emptyRegs = emptyRegFile


-- * Per-constructor input projections (v2 structural surface) -------------
--
-- One 'InCtor' value per command constructor describes how to match
-- and re-build the constructor's payload as a typed 'RegFile'. The
-- per-constructor 'inpFoo' helpers turn an 'Index' (typically written
-- via 'OverloadedLabels' as @inpStart #email@) into a 'Term' that
-- structurally projects the named field of the named command
-- constructor. 'solveOutput' walks the 'OutFields' bound by an edge's
-- @output@ and reconstructs the input @ci@ mechanically; no per-edge
-- inverse function is needed.

type StartFields   =
  '[ '("email", Email)
   , '("confirmCode", ConfirmationCode)
   , '("at", UTCTime)
   ]

type ConfirmFields =
  '[ '("confirmCode", ConfirmationCode)
   , '("at", UTCTime)
   ]

type ResendFields  =
  '[ '("code", ConfirmationCode)
   , '("at", UTCTime)
   ]

type GdprFields    =
  '[ '("at", UTCTime) ]


-- All five 'InCtor' values below are 'mkInCtorVia'-built: the
-- constructor name, the sum-side match\/wrap, the slot list, and the
-- 'RegFile' inversion are all derived from 'UserCmd' and the payload
-- record's 'Generic' instances. 'inCtorContinue' uses 'mkInCtor0'
-- because 'Continue' is a singleton value rather than a record-payload
-- constructor; 'mkInCtorVia' would also work via the unit-payload
-- 'GHasCtor' instance, but 'mkInCtor0' is the more direct expression.

inCtorStart    :: InCtor UserCmd StartFields
inCtorStart     = mkInCtorVia @"StartRegistration"

inCtorConfirm  :: InCtor UserCmd ConfirmFields
inCtorConfirm   = mkInCtorVia @"ConfirmAccount"

inCtorResend   :: InCtor UserCmd ResendFields
inCtorResend    = mkInCtorVia @"ResendConfirmation"

inCtorGdpr     :: InCtor UserCmd GdprFields
inCtorGdpr      = mkInCtorVia @"FulfillGDPRRequest"

inCtorContinue :: InCtor UserCmd '[]
inCtorContinue  = mkInCtor0 "Continue" Continue


inpStart   :: Index StartFields   r -> Term UserRegRegs UserCmd r
inpStart    = TInpCtorField inCtorStart

inpConfirm :: Index ConfirmFields r -> Term UserRegRegs UserCmd r
inpConfirm  = TInpCtorField inCtorConfirm

inpResend  :: Index ResendFields  r -> Term UserRegRegs UserCmd r
inpResend   = TInpCtorField inCtorResend

inpGdpr    :: Index GdprFields    r -> Term UserRegRegs UserCmd r
inpGdpr     = TInpCtorField inCtorGdpr


-- * Per-constructor guards -------------------------------------------------
--
-- These were 'matchCmd'-built v1 'PMatchC' atoms in earlier
-- revisions; EP-2 of MasterPlan 2 migrated them to 'matchInCtor' so
-- the SBV-backed 'BoolAlg' instance recognizes constructor mutual
-- exclusion symbolically. The v1 'evalPred' semantics is preserved:
-- @evalPred (matchInCtor ic) regs ci == isJust (icMatch ic ci)@,
-- which is identical in behavior to the pattern-match closures the
-- previous form used.

isStart, isConfirm, isResend, isGdpr, isContinue
  :: HsPred UserRegRegs UserCmd
isStart    = matchInCtor inCtorStart
isConfirm  = matchInCtor inCtorConfirm
isResend   = matchInCtor inCtorResend
isGdpr     = matchInCtor inCtorGdpr
isContinue = matchInCtor inCtorContinue


-- * Wire constructors for events -------------------------------------------

-- All five 'WireCtor' values below are 'mkWireCtorVia'-built; both
-- the sum-side match\/wrap and the nested-pair field tuple come from
-- 'UserEvent' and each event record's 'Generic' instances.

wireRegistrationStarted   :: WireCtor UserEvent (FieldsOf RegistrationStartedData)
wireRegistrationStarted    = mkWireCtorVia @"RegistrationStarted"

wireConfirmationEmailSent :: WireCtor UserEvent (FieldsOf ConfirmationEmailSentData)
wireConfirmationEmailSent  = mkWireCtorVia @"ConfirmationEmailSent"

wireAccountConfirmed      :: WireCtor UserEvent (FieldsOf AccountConfirmedData)
wireAccountConfirmed       = mkWireCtorVia @"AccountConfirmed"

wireConfirmationResent    :: WireCtor UserEvent (FieldsOf ConfirmationResentData)
wireConfirmationResent     = mkWireCtorVia @"ConfirmationResent"

wireAccountDeleted        :: WireCtor UserEvent (FieldsOf AccountDeletedData)
wireAccountDeleted         = mkWireCtorVia @"AccountDeleted"


-- * The transducer ---------------------------------------------------------

userReg :: SymTransducer (HsPred UserRegRegs UserCmd)
                         UserRegRegs
                         Vertex
                         UserCmd
                         UserEvent
userReg = SymTransducer
  { edgesOut = userRegEdges
  , initial     = PotentialCustomer
  , initialRegs = emptyRegs
  , isFinal     = \case Deleted -> True; _ -> False
  }


userRegEdges
  :: Vertex
  -> [Edge (HsPred UserRegRegs UserCmd) UserRegRegs UserCmd UserEvent Vertex]
userRegEdges = \case

  PotentialCustomer ->
    [ Edge
        { guard  = isStart
        , update =
            USet (#email :: Index UserRegRegs Email) (inpStart #email)
              `unsafeCombine`
            USet (#confirmCode :: Index UserRegRegs ConfirmationCode)
                 (inpStart #confirmCode)
              `unsafeCombine`
            USet (#registeredAt :: Index UserRegRegs UTCTime)
                 (inpStart #at)
        , output = Just $ pack
            inCtorStart
            wireRegistrationStarted
            (OFCons (inpStart #email)
              (OFCons (inpStart #confirmCode)
                (OFCons (inpStart #at) OFNil)))
        , target = Registering
        }
    ]

  -- Internal Continue command emits ConfirmationEmailSent.
  Registering ->
    [ Edge
        { guard  = isContinue
        , update = UKeep
        , output = Just $ pack
            inCtorContinue
            wireConfirmationEmailSent
            (OFCons (proj (#email :: Index UserRegRegs Email)) OFNil)
        , target = RequiresConfirmation
        }
    ]

  RequiresConfirmation ->
    [ -- Right code: confirm. The 'isConfirm' conjunct short-circuits the
      -- inpConfirm read for non-ConfirmAccount inputs.
      Edge
        { guard  = PAnd isConfirm
            (inpConfirm #confirmCode
              .== proj (#confirmCode :: Index UserRegRegs ConfirmationCode))
        , update = USet (#confirmedAt :: Index UserRegRegs UTCTime)
                        (inpConfirm #at)
        , output = Just $ pack
            inCtorConfirm
            wireAccountConfirmed
            (OFCons (proj (#email :: Index UserRegRegs Email))
              (OFCons (inpConfirm #confirmCode)
                (OFCons (inpConfirm #at) OFNil)))
        , target = Confirmed
        }
      -- Resend: rotate the code (code arrives in the command).
    , Edge
        { guard  = isResend
        , update =
            USet (#confirmCode :: Index UserRegRegs ConfirmationCode)
                 (inpResend #code)
              `unsafeCombine`
            USet (#registeredAt :: Index UserRegRegs UTCTime)
                 (inpResend #at)
        , output = Just $ pack
            inCtorResend
            wireConfirmationResent
            (OFCons (proj (#email :: Index UserRegRegs Email))
              (OFCons (inpResend #code)
                (OFCons (inpResend #at) OFNil)))
        , target = RequiresConfirmation
        }
      -- GDPR before confirmation: silent ε-edge (no event).
    , Edge
        { guard  = isGdpr
        , update = USet (#deletedAt :: Index UserRegRegs UTCTime)
                        (inpGdpr #at)
        , output = Nothing
        , target = Deleted
        }
    ]

  Confirmed ->
    [ Edge
        { guard  = isGdpr
        , update = USet (#deletedAt :: Index UserRegRegs UTCTime)
                        (inpGdpr #at)
        , output = Just $ pack
            inCtorGdpr
            wireAccountDeleted
            (OFCons (proj (#email :: Index UserRegRegs Email))
              (OFCons (inpGdpr #at) OFNil))
        , target = Deleted
        }
    ]

  Deleted -> []
